In [67]:
class parent:
#     lol = 'lol'
    def __init__(self):
        self.parent_name = 'dad'
        self.tmp = "parent_prop"
        self._x = 'here'
        self.lol = 'lol1'
    
    def change_lol(self):
        self.lol = 'lol2'
#         self.__class__.lol = 'lol2'
        
    @property
    def x(self):
        return self._x

    @x.setter
    def x(self, value):
        self._x = value
class child(parent):
    def __init__(self):
        super(child, self).__init__()
        self.child_name = 'child'
#         print(self.parant_name)

p = parent()
c = child()
p.change_lol()
p.lol
c.lol
# p.lol
# p.__class__.lol


'lol1'

In [80]:
# 2 * (self.data * np.expand_dims(self.data.dot(v["val"]), axis=1) + 2 * args.lmda * v["val"].squeeze()).sum(axis =0)
lmda= 0.0
import numpy as np
data = np.arange(9).reshape(3,3) + 1
v = {}
v['val'] = np.ones(3)
func = 2 * (data * np.expand_dims(data.dot(v["val"]), axis=1) + 2 * lmda * v["val"].squeeze()).sum(axis =0)
func # is this correct?? 

array([468., 558., 648.])

In [70]:
import numpy as np
data = np.arange(9)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
np.ones(2).shape

(2,)

In [81]:
np.expand_dims(data.dot(v["val"]), axis=1)


array([[ 6.],
       [15.],
       [24.]])

In [116]:
data # (3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
v['val'] # (3,)

array([1., 1., 1.])

In [118]:
y = np.arange(3).reshape(3,1)
y

array([[0],
       [1],
       [2]])

In [89]:
# (data * np.expand_dims(data.dot(v["val"]), axis=1)).sum(axis=0)  2 * lmda * v["val"].squeeze()).sum(axis =0)

array([234., 279., 324.])

In [119]:
(y - data.dot(v["val"].T)).dot(data) + 2 * lmda * v['val']

array([[-233.98, -278.98, -323.98],
       [-221.98, -263.98, -305.98],
       [-209.98, -248.98, -287.98]])

In [107]:
data.dot(v["val"].T) # (3,)

array([ 6., 15., 24.])

In [120]:
y - data.dot(v["val"].T)

array([[ -6., -15., -24.],
       [ -5., -14., -23.],
       [ -4., -13., -22.]])

In [112]:
tmp = np.arange(3).reshape(1,3)
tmp1 = np.ones((3,)) * 2
tmp.dot(tmp1)

array([6.])

In [113]:
tmp1

array([2., 2., 2.])

In [95]:
data * np.expand_dims(data.dot(v["val"]), axis=1)

array([[ 6.],
       [15.],
       [24.]])

In [103]:
lmda= 0.01
data.dot(v['val'].T).shape


(3,)